import {execFileSync,spawn} from 'node:child_process';
import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {tmpdir} from 'node:os';
import {validateJson} from '../skills/aiglot-localize-repo/scripts/validate-json.mjs';
const flags=process.argv.slice(2),at=flags.indexOf('--max-credits'),budget=Number(flags[at+1]);
if(!flags.includes('--approve')||!Number.isFinite(budget)||budget<=0)throw Error('Explicit --approve --max-credits required. Use only synthetic fixtures.');
const qualityAt=flags.indexOf('--quality'),quality=qualityAt<0?'lite':flags[qualityAt+1];
if(!['lite','standard'].includes(quality))throw Error('Quality must be lite or standard');
const profileAt=flags.indexOf('--profile'),profileArgs=profileAt<0?[]:['--profile',flags[profileAt+1]];
const workspaceAt=flags.indexOf('--workspace-name'),expectedWorkspace=workspaceAt<0?null:flags[workspaceAt+1];
const reportAt=flags.indexOf('--report');
const root=resolve(import.meta.dirname,'..'),dir=mkdtempSync(join(tmpdir(),'aiglot-directory-smoke-'));
const cli=args=>JSON.parse(execFileSync('aiglot',[...args,...profileArgs,'--json'],{encoding:'utf8',timeout:180000,maxBuffer:10000000}));
const rpc=(method,params)=>new Promise((resolve,reject)=>{const p=spawn('aiglot',['mcp',...profileArgs],{stdio:['pipe','pipe','ignore']});let out='';const timer=setTimeout(()=>{p.kill();reject(Error('MCP timeout'));},60000);p.stdout.on('data',x=>out+=x);p.on('error',reject);p.on('close',code=>{clearTimeout(timer);try{if(code)throw Error('MCP bridge failed');const result=JSON.parse(out.trim().split('\n').at(-1));if(result.error)throw Error('MCP protocol error');resolve(result.result);}catch(e){reject(e);}});p.stdin.end(JSON.stringify({jsonrpc:'2.0',id:1,method,params})+'\n');});
const call=(name,args)=>rpc('tools/call',{name,arguments:args});const data=r=>{if(r.isError)throw Error(r.structuredContent?.error?.code??'tool error');return r.structuredContent;};
const catalog=await rpc('tools/list',{});for(const t of catalog.tools)for(const hint of ['readOnlyHint','destructiveHint','openWorldHint'])if(typeof t.annotations?.[hint]!=='boolean')throw Error('Missing tool annotation: '+t.name+'.'+hint);
const resource=await rpc('resources/read',{uri:'ui://aiglot/translation-review-v1.html'});if(resource.contents[0].mimeType!=='text/html;profile=mcp-app')throw Error('MCP UI resource missing');
const a=data(await call('get_account',{}));if(expectedWorkspace&&a.workspace.name!==expectedWorkspace)throw Error('Unexpected workspace; no writes performed');if(!a.entitlements.quality_tiers.includes(quality))throw Error('Requested quality unavailable');
data(await call('get_credit_balance',{}));data(await call('get_usage',{}));
const resumeAt=flags.indexOf('--resume-file');
const previous=resumeAt<0?[]:JSON.parse(readFileSync(flags[resumeAt+1],'utf8'));
const jobs=[['messages.json','French','json'],['messages.json','German','json'],['guide.docx','German','docx'],['catalog.csv','French','csv']];let total=0;const plans=[];
for(const [file,language,format] of jobs){const instruction=format==='csv'?`The source is English. Translate only description column values into ${language}. Preserve SKU, price, headers and row order.`:`The source is English. Translate all text values into ${language}. Preserve keys, placeholders and formatting.`;const saved=previous.find(x=>x.file===file&&x.language===language);let batch;
if(saved){batch={id:saved.id};}
else if(format==='docx'){
 const bytes=readFileSync(resolve(root,'packaging/review/fixtures',file));
 const upload=data(await call('create_upload_url',{filename:'directory-review-'+language.toLowerCase()+'-'+file,size_bytes:bytes.length}));
 const put=await fetch(upload.upload_url,{method:'PUT',headers:upload.headers,body:bytes,redirect:'error',signal:AbortSignal.timeout(60000)});
 if(!put.ok)throw Error('Synthetic binary upload failed');
 batch=data(await call('create_translation',{upload_id:upload.upload_id,instruction}));
}else{batch=cli(['batches','create',resolve(root,'packaging/review/fixtures',file),'--name','directory-review-'+language.toLowerCase()+'-'+file,'--instruction',instruction]);}
const current=data(await call('get_batch',{batch_id:batch.id}));if(current.status!=='awaiting_approval'||!current.plan_revision||current.plan.not_included.length)throw Error('Plan incomplete or exclusions need review');const quote=current.plan.credits[quality];if(!Number.isFinite(quote)||quote<0)throw Error('Invalid measured quote');total+=quote;if(total>budget||total>a.credit_balance)throw Error('Combined measured quote exceeds authorized ceiling');data(await call('show_translation',{batch_id:batch.id}));plans.push({id:batch.id,file,format,language,revision:current.plan_revision,quote});writeFileSync(join(dir,'private-jobs.json'),JSON.stringify(plans));}
console.log(JSON.stringify({phase:'planned',jobs:plans.length,quality,combined_quote:total,ceiling:budget,tool_count:catalog.tools.length}));
const first=plans[0],wrong=(first.revision[0]==='a'?'b':'a')+first.revision.slice(1);const refused=await call('approve_translation',{batch_id:first.id,quality,expected_plan_revision:wrong});if(!refused.isError||refused.structuredContent?.error?.code!=='plan_changed')throw Error('Stale revision was not refused');
const evidence=[];
for(const job of plans){data(await call('approve_translation',{batch_id:job.id,quality,expected_plan_revision:job.revision}));let batch;for(let i=0;i<90;i++){batch=cli(['batches','get',job.id]);if(['completed','failed','cancelled'].includes(batch.status))break;await new Promise(r=>setTimeout(r,3000));}if(batch?.status!=='completed')throw Error('Synthetic run did not finish; recover from private-jobs.json');const output=join(dir,job.language.toLowerCase()+'-'+job.file);execFileSync('aiglot',['batches','download',job.id,'--output',output,...profileArgs],{encoding:'utf8',timeout:60000});if(job.format==='json'){const original=JSON.parse(readFileSync(resolve(root,'packaging/review/fixtures',job.file),'utf8')),target=JSON.parse(readFileSync(output,'utf8'));validateJson(original,target);if(target.greeting===original.greeting)throw Error('JSON result unchanged');}else if(job.format==='csv'){const value=readFileSync(output,'utf8');if(!value.includes('SKU-001')||!value.includes('SKU-002')||!value.includes('19.90')||!value.includes('29.90')||value.includes('Light cotton shirt')||value.includes('Waterproof travel bag')||!value.startsWith('sku,description,price'))throw Error('CSV identity or price changed');}else {execFileSync('python3',['-c','import zipfile,sys;from xml.etree import ElementTree as E;z=zipfile.ZipFile(sys.argv[1]);x=E.fromstring(z.read("word/document.xml"));ns={"w":"http://schemas.openxmlformats.org/wordprocessingml/2006/main"};assert x.find(".//w:b",ns) is not None;assert "{name}" in "".join(x.itertext());assert "Hello {name}. Keep this document safe." not in "".join(x.itertext())',output]);}evidence.push({format:job.format,target:job.language,status:'passed',credit_cost:batch.credit_cost,structure_verified:true});console.log(JSON.stringify(evidence.at(-1)));}
const report={checked_at:new Date().toISOString(),transport:'CLI and authenticated MCP bridge; not in-host UI acceptance',tool_count:catalog.tools.length,annotations_verified:true,ui_resource_verified:true,stale_revision_rejected:true,quality,authorized_ceiling:budget,credits_spent:evidence.reduce((n,x)=>n+x.credit_cost,0),jobs:evidence};writeFileSync(reportAt<0?resolve(root,'packaging/review/live-evidence.json'):resolve(flags[reportAt+1]),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
